# Generated by Django 5.1.7 on 2025-05-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id_book', models.AutoField(primary_key=True, serialize=False)),
                ('name_book', models.CharField(max_length=64, verbose_name='Назззззвание книги')),
                ('author_book', models.CharField(max_length=64, verbose_name='Автор книги')),
                ('price_book', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена книги')),
                ('genre_book', models.CharField(max_length=64, verbose_name='Жанр книги')),
                ('publication_year_book', models.IntegerField(verbose_name='Год публикации книги')),
                ('publisher_book', models.CharField(max_length=64, verbose_name='Издательство книги')),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
